import type { AdminDatabase } from '@/lib/admin/types';

const now = new Date().toISOString();

export const initialAdminDatabase: AdminDatabase = {
  leads: [
    {
      id: 'lead_1',
      name: 'Carlos Oliveira',
      email: 'carlos.o@email.com',
      city: 'Sao Paulo, SP',
      area: 'Front-end',
      technologies: ['React', 'Next.js', 'Tailwind'],
      experienceLevel: 'Senior',
      availability: '10-20h/semana',
      motivation: 'Contribuir em projetos de impacto politico com alta qualidade tecnica.',
      github: 'https://github.com/carlos',
      linkedin: 'https://linkedin.com/in/carlos',
      status: 'novo',
      notes: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lead_2',
      name: 'Ana Souza',
      email: 'ana.souza@email.com',
      city: 'Rio de Janeiro, RJ',
      area: 'Dados',
      technologies: ['Python', 'SQL', 'Power BI'],
      experienceLevel: 'Pleno',
      availability: '5-10h/semana',
      motivation: 'Atuar em inteligencia de dados para fortalecer mobilizacao.',
      github: 'https://github.com/anasouza',
      linkedin: 'https://linkedin.com/in/anasouza',
      status: 'em_analise',
      notes: 'Perfil aderente para squad de dados.',
      createdAt: now,
      updatedAt: now,
    },
  ],
  formSubmissions: [
    {
      id: 'form_1',
      formType: 'voluntarios_tech',
      name: 'Carlos Oliveira',
      email: 'carlos.o@email.com',
      subject: 'Inscricao voluntario tech',
      message: 'Tenho experiencia com React/Next e posso colaborar no front.',
      linkedLeadId: 'lead_1',
      createdAt: now,
    },
    {
      id: 'form_2',
      formType: 'contato_geral',
      name: 'Mariana Lima',
      email: 'mariana@email.com',
      subject: 'Parceria institucional',
      message: 'Quero apresentar iniciativa de transparencia local para avaliacao.',
      createdAt: now,
    },
  ],
  projects: [
    {
      id: 'proj_1',
      name: 'Plataforma Missao',
      slug: 'plataforma-missao',
      subtitle: 'Hub tecnologico politico',
      shortDescription: 'Plataforma principal do laboratorio.',
      longDescription:
        'Centraliza projetos, equipe, contribuicoes e recrutamento tech em uma base unica.',
      categoryId: 'cat_1',
      objectiveIds: ['obj_1', 'obj_2'],
      tagIds: ['tag_1', 'tag_2'],
      status: 'publicado',
      externalLink: 'https://missao.org',
      stack: ['Next.js', 'TypeScript', 'Tailwind', 'Firebase'],
      metrics: [
        { label: 'Leads', value: '156' },
        { label: 'Projetos', value: '24' },
      ],
      gallery: ['https://picsum.photos/seed/proj1/1200/700'],
      roadmap: ['Concluir APIs', 'Implementar auditoria', 'Publicar modulo de contribuicoes'],
      teamIds: ['mem_1', 'mem_2'],
      featured: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  members: [
    {
      id: 'mem_1',
      name: 'Felipe Pires',
      role: 'Tech Lead / Architect',
      shortBio: 'Lideranca tecnica e arquitetura de plataforma.',
      longBio: 'Responsavel por arquitetura, padroes tecnicos e evolucao da base.',
      stack: ['TypeScript', 'Next.js', 'Node.js', 'PostgreSQL'],
      hoursDedicated: 450,
      projectIds: ['proj_1'],
      badges: ['Arquitetura', 'Lideranca'],
      github: 'https://github.com/fpires',
      linkedin: 'https://linkedin.com/in/felipe-pires',
      instagram: 'https://instagram.com/fpires.tech',
      email: 'felipe@missao.org',
      status: 'ativo',
      featured: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'mem_2',
      name: 'Ana Silva',
      role: 'Product Designer',
      shortBio: 'Design de produto e experiencia.',
      longBio: 'Conduz sistema visual e fluxos de alta clareza para publico e operacao interna.',
      stack: ['Figma', 'UX', 'Design System'],
      hoursDedicated: 320,
      projectIds: ['proj_1'],
      badges: ['UX', 'Design System'],
      github: 'https://github.com/anadesign',
      linkedin: 'https://linkedin.com/in/ana-silva-ux',
      instagram: 'https://instagram.com/ana.ux',
      email: 'ana@missao.org',
      status: 'ativo',
      featured: false,
      createdAt: now,
      updatedAt: now,
    },
  ],
  contributions: [
    {
      id: 'cont_1',
      memberId: 'mem_1',
      projectId: 'proj_1',
      role: 'Tech Lead',
      description: 'Arquitetura inicial e padrao de componentes.',
      hours: 120,
      period: 'Q1 2026',
      date: now,
      createdAt: now,
    },
  ],
  categories: [
    { id: 'cat_1', name: 'Infraestrutura Politica', description: 'Projetos estruturantes da operacao.' },
    { id: 'cat_2', name: 'Transparencia Politica', description: 'Projetos de visibilidade e controle social.' },
  ],
  objectives: [
    { id: 'obj_1', name: 'Mobilizacao', description: 'Aumentar capacidade de engajamento.' },
    { id: 'obj_2', name: 'Governanca Digital', description: 'Estruturar operacao com dados e processos.' },
  ],
  tags: [
    { id: 'tag_1', name: 'interativo' },
    { id: 'tag_2', name: 'visualizacao de dados' },
    { id: 'tag_3', name: 'timeline' },
  ],
  media: [
    {
      id: 'media_1',
      name: 'hero-plataforma.jpg',
      url: 'https://picsum.photos/seed/media1/1200/700',
      mimeType: 'image/jpeg',
      size: 248220,
      createdAt: now,
    },
  ],
  settings: {
    heroTitle: 'O futuro e tecnologico.',
    heroSubtitle:
      'Laboratorio de inovacao politica com foco em engenharia, dados e mobilizacao.',
    heroCtaLabel: 'Quero participar',
    heroCtaUrl: '/participe',
    institutionalText:
      'Hub de tecnologia politica da equipe de Ludymilla Dias no ecossistema do Partido Missao.',
    homeMetrics: [
      { label: 'Projetos', value: '24' },
      { label: 'Voluntarios', value: '48' },
      { label: 'Leads', value: '156' },
      { label: 'Impacto', value: '150K+' },
    ],
    globalLinks: [
      { label: 'Site Ludymilla', url: 'https://aludydias.com.br' },
      { label: 'Participe', url: '/participe' },
    ],
    socials: [
      { network: 'Instagram', url: 'https://instagram.com/ludymilladias' },
      { network: 'LinkedIn', url: 'https://linkedin.com' },
    ],
    seoTitle: 'Missao Lab | Ludymilla Dias',
    seoDescription: 'Plataforma de tecnologia politica e mobilizacao digital.',
    footerText: 'Construindo a infraestrutura civica do futuro.',
  },
  activities: [
    { id: 'act_1', type: 'lead', description: 'Novo lead recebido: Carlos Oliveira', createdAt: now },
    { id: 'act_2', type: 'project', description: 'Projeto Plataforma Missao publicado', createdAt: now },
  ],
};
